"""
Project model representing a complete home automation configuration.
"""

import json
from models.module import Module

class Project:
    """Represents a complete home automation project with multiple modules."""

    def __init__(self, name="Untitled Project"):
        self.name = name
        self.modules = []
        self.modified = False

    def add_module(self, module):
        self.modules.append(module)
        self.modified = True

    def to_c_code(self):
        lines = [
            f"// Project: {self.name}",
            f"// Generated by EventAction Configurator",
            ""
        ]
        for module in self.modules:
            lines.append("")
            lines.append(module.to_c_code())
        return "\n".join(lines)

    def validate(self):
        errors = []
        for module in self.modules:
            module_errors = module.validate()
            if module_errors:
                errors.append(f"Module {module.name}:")
                errors.extend([f"  - {err}" for err in module_errors])
        return errors

    def to_dict(self):
        return {
            "name": self.name,
            "modules": [module.to_dict() for module in self.modules]
        }

    def save_to_file(self, filepath):
        with open(filepath, 'w') as f:
            json.dump(self.to_dict(), f, indent=2)
        self.modified = False

    @classmethod
    def from_dict(cls, data):
        project = cls(name=data.get("name", "Untitled Project"))
        legacy_light_points = data.get("light_points", {})

        # Support both "modules" and legacy "devices" key
        modules_data = data.get("modules", data.get("devices", []))

        for module_data in modules_data:
            module = Module.from_dict(module_data)
            if not module.outputs and legacy_light_points:
                module.outputs = {k: list(v) for k, v in legacy_light_points.items()}
            project.modules.append(module)

        # Build shared outputs pool from output modules (num_inputs == 0)
        shared_outputs = {}
        for module in project.modules:
            if module.num_inputs == 0:
                shared_outputs.update(module.outputs)

        # Assign shared outputs to switch modules that have none
        if shared_outputs:
            for module in project.modules:
                if module.num_inputs > 0 and not module.outputs:
                    module.outputs = dict(shared_outputs)

        project.modified = False
        return project

    @classmethod
    def load_from_file(cls, filepath):
        with open(filepath, 'r') as f:
            data = json.load(f)
        return cls.from_dict(data)

    def __repr__(self):
        return f"Project({self.name}, modules={len(self.modules)})"
