"""
Project model representing a complete home automation configuration.
"""

import json
from models.device import Device

class Project:
    """Represents a complete home automation project with multiple devices."""
    
    def __init__(self, name="Untitled Project"):
        self.name = name
        self.devices = []
        self.light_points = {}
        self.modified = False
    
    def add_device(self, device):
        """Add a device to the project."""
        self.devices.append(device)
        self.modified = True
    
    def remove_device(self, device_name):
        """Remove a device by name."""
        self.devices = [d for d in self.devices if d.name != device_name]
        self.modified = True
    
    def get_device(self, device_name):
        """Get a device by name."""
        for device in self.devices:
            if device.name == device_name:
                return device
        return None
    
    def set_light_points(self, light_points_dict):
        """Set the light points configuration."""
        self.light_points = light_points_dict
        self.modified = True
    
    def to_c_code(self):
        """Generate C code for all devices."""
        lines = [
            f"// Project: {self.name}",
            f"// Generated by EventAction Configurator",
            ""
        ]
        
        for device in self.devices:
            lines.append("")
            lines.append(device.to_c_code())
        
        return "\n".join(lines)
    
    def validate(self):
        """Validate all devices in the project."""
        errors = []
        
        for device in self.devices:
            device_errors = device.validate()
            if device_errors:
                errors.append(f"Device {device.name}:")
                errors.extend([f"  - {err}" for err in device_errors])
        
        return errors
    
    def to_dict(self):
        """Convert project to dictionary for JSON serialization."""
        return {
            "name": self.name,
            "light_points": self.light_points,
            "devices": [device.to_dict() for device in self.devices]
        }
    
    def save_to_file(self, filepath):
        """Save project to JSON file."""
        with open(filepath, 'w') as f:
            json.dump(self.to_dict(), f, indent=2)
        self.modified = False
    
    @classmethod
    def from_dict(cls, data):
        """Create project from dictionary."""
        project = cls(name=data.get("name", "Untitled Project"))
        project.light_points = data.get("light_points", {})
        
        for device_data in data.get("devices", []):
            device = Device.from_dict(device_data)
            project.devices.append(device)
        
        project.modified = False
        return project
    
    @classmethod
    def load_from_file(cls, filepath):
        """Load project from JSON file."""
        with open(filepath, 'r') as f:
            data = json.load(f)
        return cls.from_dict(data)
    
    def __repr__(self):
        return f"Project({self.name}, devices={len(self.devices)})"
