"""
Project model representing a complete home automation configuration.
"""

import json
from models.module import Module

class Project:
    """Represents a complete home automation project with multiple modules."""

    def __init__(self, name="Untitled Project"):
        self.name = name
        self.modules = []
        self.api_base_url = ""
        self.api_token = ""
        self.api_token_session_only = False
        self.modified = False

    def add_module(self, module):
        self.modules.append(module)
        self.modified = True

    def to_c_code(self):
        lines = [
            f"// Project: {self.name}",
            f"// Generated by Domoriks Configurator",
            ""
        ]
        for module in self.modules:
            lines.append("")
            lines.append(module.to_c_code())
        return "\n".join(lines)

    def validate(self):
        errors = []
        for module in self.modules:
            module_errors = module.validate()
            if module_errors:
                errors.append(f"Module {module.name}:")
                errors.extend([f"  - {err}" for err in module_errors])
        return errors

    def to_dict(self):
        data = {
            "name": self.name,
            "modules": [module.to_dict() for module in self.modules],
        }
        data["api"] = {
            "base_url": self.api_base_url,
            "token": self.api_token,
            "token_session_only": self.api_token_session_only,
        }
        return data

    def save_to_file(self, filepath, preserve_existing_token=False):
        data = self.to_dict()
        if preserve_existing_token:
            data.setdefault("api", {})["token"] = ""
            try:
                with open(filepath, 'r') as f:
                    existing = json.load(f)
                existing_api = existing.get("api", {}) if isinstance(existing.get("api", {}), dict) else {}
                existing_token = existing_api.get("token", "")
                if existing_token:
                    data.setdefault("api", {})["token"] = existing_token
            except FileNotFoundError:
                pass
            except Exception:
                pass

        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        self.modified = False

    @classmethod
    def from_dict(cls, data):
        project = cls(name=data.get("name", "Untitled Project"))
        legacy_light_points = data.get("light_points", {})

        api_data = data.get("api", {}) if isinstance(data.get("api", {}), dict) else {}
        project.api_base_url = api_data.get("base_url", "") or ""
        project.api_token = api_data.get("token", "") or ""
        project.api_token_session_only = bool(api_data.get("token_session_only", False))

        # Support both "modules" and legacy "devices" key
        modules_data = data.get("modules", data.get("devices", []))

        for module_data in modules_data:
            module = Module.from_dict(module_data)
            if not module.outputs and legacy_light_points:
                module.outputs = {
                    k: int(v[1]) if isinstance(v, (list, tuple)) else int(v)
                    for k, v in legacy_light_points.items()
                }
            project.modules.append(module)

        project.modified = False
        return project

    @classmethod
    def load_from_file(cls, filepath):
        with open(filepath, 'r') as f:
            data = json.load(f)
        return cls.from_dict(data)

    def __repr__(self):
        return f"Project({self.name}, modules={len(self.modules)})"
